apiVersion: v1
kind: Service
metadata:
  labels:
    app: guestbook-ui
  name: guestbook-ui
  namespace: argocd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook-ui
  type: NodePort
